### ISSUE TITLE
issues using xssShield()

### ISSUE THREAD

**Issue by MichalPlatosz1** [Louis3797/xss-shield#24]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Trying to use xss-shield as:
const xssShield = require("xss-shield");
app.use(xssShield());

throws back an error:

TypeError: xssShield is not a function

**Comment by fabricelejeune** [comment]
I have the same issue.
You have to do like this:

```
import xss from 'xss-shield';
app.use(xss.xssShield());
```
