### ISSUE TITLE
Integration with typeScript

### ISSUE THREAD

**Issue by Shrief88** [Louis3797/xss-shield#25]
- **I'm submitting a ...**
  [ ] bug report

- **Summary**
I am trying to import the package in my express typeScript app like that: 
import xssShield from "xss-shield";
app.use(xssShield());
I am getting error that xssShield is not callable

**Comment by fabricelejeune** [comment]
I have the same issue.
You have to do like this:

```
import xss from 'xss-shield';
app.use(xss.xssShield());
```
